Repository PeopleForBikes/bna-website, pull requests merged in 2023-04, with the labels that each got.

#1 initial folder/files
  .eslintrc.js
  .eslintrc.json
  .gitignore
  next.config.js
  package.json
  public/favicon/BNA Mechanics logo-03.svg
  public/favicon/BNA Mechanics logo-small.svg
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/icon.svg
  public/favicon/pfb-small.png
  public/favicon/pfb-small.xcf
  public/favicon/pfb.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
  public/next.svg
  public/vercel.svg
  src/app/(LandingPage)/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/assets/fonts/DharmaGothicE-ExBold.otf
  src/assets/fonts/DharmaGothicE-ExLight.otf
  src/assets/styles/base.css
  src/assets/styles/fonts.css
  src/assets/styles/layout.css
  src/assets/styles/resets.css
  src/assets/styles/themes.css
  tsconfig.json
Labels: size/XL

#2 Update Dependabot congifuration
  .github/dependabot.yml
Labels: size/XS

#8 Clean up
  package.json
  pnpm-lock.yaml
  postcss.config.js
  public/favicon/BNA Mechanics logo-03.svg
  public/favicon/BNA Mechanics logo-small.svg
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/manifest.webmanifest
  public/favicon/pfb-small.png
  public/favicon/pfb-small.xcf
  public/favicon/pfb.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
  src/app/(LandingPage)/page.tsx
  src/app/api/hello/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/assets/fonts/Montserrat-Medium.otf
  src/assets/fonts/Montserrat-Regular.otf
  src/assets/fonts/Montserrat-SemiBold.otf
  src/assets/images/logo-bna-full-1015×596.png
  src/assets/images/logo-bna-full-dark-white-text-1015×597.png
  src/assets/styles/base.css
  src/assets/styles/fonts.css
  src/components/Footer/index.tsx
  src/components/Footer/styles.module.css
  src/components/Header/index.tsx
  src/components/Header/styles.module.css
  src/components/index.ts
  tailwind.config.js
Labels: size/XXL
